[package]
name = "rivet-model"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
rivet-types = { workspace = true }
accp = { workspace = true }
noesis = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
reqwest = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

