[package]
name = "rivet-model-genai"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
rivet-types = { workspace = true }
rivet-model = { workspace = true }
reqwest = { workspace = true }
dotenvy = { workspace = true }
futures-util = { workspace = true }
async-trait = { workspace = true }
serde_json = { workspace = true }
eventsource-stream = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
noesis = { workspace = true }
rivet-types = { workspace = true }

