[package]
name = "rivet-model-genai"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
rivet-types = { workspace = true }
rivet-model = { workspace = true }
genai = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
