import type { ModelCatalog, Project } from '../types'

type Props = { project: Project | null; models: ModelCatalog | null; connection: string; onProject: () => void; onModel: () => void; onSettings: () => void; onProjectSettings: () => void; projectOpen: boolean; modelOpen: boolean; settingsOpen: boolean; onPickModel: (provider: string, model: string) => void }

export function AppHeader({ project, models, connection, onProject, onModel, onSettings, onProjectSettings, projectOpen, modelOpen, settingsOpen, onPickModel }: Props) {
  return <header className="topbar">
    <div className="project-cluster"><button className="project-button" aria-expanded={projectOpen} onClick={onProject}><span className="mark"><i /></span><span className="repo-name">{project?.name ?? 'rivet'}</span><span className="branch">{project?.branch ?? 'local workspace'} · {project?.revision ? `rev ${project.revision}` : 'uncommitted'}</span><span aria-hidden="true">⌄</span></button>
      {projectOpen && <div className="popover project-menu"><div className="menu-current"><b>{project?.path ?? 'Rivet workspace'}</b><small>{project?.dirty ? 'working tree has changes' : 'working tree clean'}</small></div><button onClick={onProjectSettings}><b>Project settings</b><small>trust · indexing · environment</small></button></div>}
    </div>
    <div className="product-controls"><span className={`connection ${connection}`}><i />{connection}</span><div className="menu-anchor"><button className="model-button" onClick={onModel} aria-label={`Select model ${models?.active_model ?? 'unavailable'}`} aria-expanded={modelOpen}><b>{models?.active_model ?? 'model unavailable'}</b><span>{models?.active_provider ?? 'provider'}</span><span>⌄</span></button>{modelOpen && <div className="popover model-menu">{models?.providers.length ? models.providers.map(provider => <section key={provider.id}><div className="provider-heading"><b>{provider.name}</b><small>{provider.configured ? 'configured' : 'catalog'}</small></div>{provider.models.slice(0, 8).map(model => <button key={`${provider.id}:${model}`} className={models.active_model === model && models.active_provider === provider.id ? 'selected' : ''} onClick={() => onPickModel(provider.id, model)}><b>{model}</b><small>{provider.id}</small></button>)}</section>) : <p className="menu-empty">Model catalog unavailable until the adapter connects.</p>}</div>}</div><button className="icon-button" aria-label="Open settings" onClick={onSettings}><svg viewBox="0 0 24 24"><path d="M12 8.5a3.5 3.5 0 1 0 0 7 3.5 3.5 0 0 0 0-7Z"/><path d="M19 12a7.3 7.3 0 0 0-.1-1l2-1.6-2-3.4-2.4 1a8.3 8.3 0 0 0-1.8-1L14.4 3h-4.8l-.4 3a8.3 8.3 0 0 0-1.8 1L5 6 3 9.4 5.1 11a7.3 7.3 0 0 0 0 2L3 14.6 5 18l2.4-1a8.3 8.3 0 0 0 1.8 1l.4 3h4.8l.4-3a8.3 8.3 0 0 0 1.8-1l2.4 1 2-3.4-2.1-1.6a7.3 7.3 0 0 0 .1-1Z"/></svg></button>{settingsOpen && <div className="popover settings-menu"><div><span>Project trust</span><b>LOCAL</b></div><div><span>Workspace writes</span><b>HARNESS-GATED</b></div><div><span>Network</span><b>POLICY LED</b></div><div><span>Reasoning surface</span><b>TYPED SUMMARY</b></div></div>}</div>
  </header>
}
