import type { Activity, Diff, Project } from '../types'

export function Aperture({ activity, onClose }: { activity: Activity; onClose: () => void }) { return <dialog open className="aperture" aria-labelledby="aperture-title"><header><span>{activity.authoritative ? 'Authoritative event' : 'Event inspection'}</span><button type="button" onClick={onClose} aria-label="Close event inspection">×</button></header><div className="aperture-title"><b id="aperture-title">{activity.kind}</b><p>{activity.body}</p></div><dl>{activity.detail.map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl></dialog> }

export function ProjectSettings({ project, onClose }: { project: Project | null; onClose: () => void }) { return <Modal title="Project settings" onClose={onClose}><div className="settings-grid"><div><span>repository</span><b>{project?.name ?? 'unavailable'}</b></div><div><span>path</span><code>{project?.path ?? 'adapter offline'}</code></div><div><span>revision</span><code>{project?.revision ?? '—'}</code></div><div><span>branch</span><code>{project?.branch ?? 'detached / unavailable'}</code></div><div><span>working tree</span><b>{project?.dirty ? 'CHANGES PRESENT' : 'CLEAN / UNKNOWN'}</b></div><div><span>authority</span><b>HARNESS-GATED</b></div></div><p className="dialog-note">Project switching is intentionally scoped to the service working directory. The adapter must expose a project manager before another repository can be opened safely.</p></Modal> }

export function ImplementationStudio({ diff, onClose }: { diff: Diff | null; onClose: () => void }) { return <Modal title="Implementation Studio" onClose={onClose} wide><div className="studio-head"><span>{diff?.files.length ?? 0} files · {diff?.status ?? 'loading'}</span><span>raw adapter diff</span></div><pre className="diff-view">{diff?.text || 'No working tree diff returned by the adapter.'}</pre><p className="dialog-note">This view is on demand. Close it to return to the same cognitive run context.</p></Modal> }

export function AuthorityDialog({ capability, target, onDecision, onClose }: { capability: string; target: string; onDecision: (decision: string) => void; onClose: () => void }) { return <div className="modal-backdrop"><dialog open className="authority-modal" aria-labelledby="authority-title"><div className="panel-label">Authority requested</div><h2 id="authority-title">{capability}</h2><p>Rivet is asking the Harness to authorize an action on <code>{target}</code>. Review the scope before deciding.</p><div className="dialog-actions"><button type="button" className="primary-action" onClick={() => onDecision('approved')}>Approve</button><button type="button" onClick={() => onDecision('denied')}>Deny</button><button type="button" onClick={onClose}>Later</button></div></dialog></div> }

function Modal({ title, children, onClose, wide = false }: { title: string; children: React.ReactNode; onClose: () => void; wide?: boolean }) { return <div className="modal-backdrop"><dialog open className={`dialog ${wide ? 'dialog-wide' : ''}`} aria-labelledby={`${title.replaceAll(' ', '-').toLowerCase()}-title`}><header><div><span className="panel-label">Rivet surface</span><h2 id={`${title.replaceAll(' ', '-').toLowerCase()}-title`}>{title}</h2></div><button type="button" onClick={onClose} aria-label={`Close ${title}`}>×</button></header>{children}</dialog></div> }
